name: Turtleduck
main: com.sorenstudios.turtleduck.Turtleduck
version: ${version}

commands:
   sos:
      description: Contacts the admins ASAP.
      usage: /sos [message]
      permission: turtleduck.sos
      permission-message: You don't have permission to contact the admins.
   batsignal:
      description: Alias for /sos.
      usage: /batsignal [message]
      permissions: turtleduck.sos
      permission-message: You don't have permission to contact the admins.